### ISSUE TITLE
Hark! For a scalable workflow descendeth upon us.

### ISSUE THREAD

**Issue by bcfriesen** [rcthomas/resist#8]
We should codify a workflow and release schedule. I would advocate for a few things that will make everybody's life easier, and welcome comments:

- timed releases (as opposed to feature-driven releases)
- pull-only model; @rcthomas should be the only person who has write access to this repository
- every commit should compile and run correctly; "work-in-progress" commits do not belong anywhere in this repository
- compilation with `-Wall -Werror` (or the equivalent for non-GCC compilers) should succeed on every commit

**Comment by rcthomas** [comment]
Sounds good.  I add:

* @rcthomas shall wait before merging his own pull requests until another person has commented on it.

**Comment by bcfriesen** [comment]
Ah yes, very good. I approved your PR, so when you merge it, feel free to resolve this issue.
